[package]
name = "agent_world_wasm_router"
version = "0.1.0"
edition = "2021"

[dependencies]
agent_world_wasm_abi = { path = "../agent_world_wasm_abi" }
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
