[package]
name = "agent_world_net"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[features]
default = []
libp2p = ["agent_world/libp2p"]

[dependencies]
agent_world = { path = "../agent_world", default-features = false }
agent_world_proto = { path = "../agent_world_proto" }
